version: '3'

services:
  client:
    image: eventos.io.client
    build: ./client
    volumes:
      - ./client:/app
  
  serverApi:
    image: eventos.io.services.api:prod
    build: 
      context: ./server/src/Eventos.IO.Services.Api
      dockerfile: Dockerfile.prod
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production
  
  nginx:
    image: eventos.io.proxy
    build: ./nginx
    ports:
      - "80:80"
      - "8287:8286"
    links:
      - client
      - serverApi