// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Eventos.IO.TestesAutomatizados.CadastroOrganizador
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CadastroDeOrganizadorFeature : Xunit.IClassFixture<CadastroDeOrganizadorFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CadastroDeOrganizador.feature"
#line hidden
        
        public CadastroDeOrganizadorFeature(CadastroDeOrganizadorFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Cadastro de Organizador", "\tUm organizador fará seu cadastro pelo site\r\n\tpara poder gerenciar seus próprios " +
                    "eventos\r\n\tAo terminar o cadastro receberá uma notificação\r\n\tde sucesso ou de fal" +
                    "ha.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Cadastro de Organizador com Sucesso")]
        [Xunit.TraitAttribute("FeatureTitle", "Cadastro de Organizador")]
        [Xunit.TraitAttribute("Description", "Cadastro de Organizador com Sucesso")]
        [Xunit.TraitAttribute("Category", "TesteAutomatizadoCadastroDeOrganizadorComSucesso")]
        public virtual void CadastroDeOrganizadorComSucesso()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cadastro de Organizador com Sucesso", new string[] {
                        "TesteAutomatizadoCadastroDeOrganizadorComSucesso"});
#line 9
this.ScenarioSetup(scenarioInfo);
#line 10
 testRunner.Given("que o Organizador está no site, na página inicial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 11
 testRunner.And("clica no link de registro", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Campo",
                        "Valor"});
            table1.AddRow(new string[] {
                        "nome",
                        "Elton Diego"});
            table1.AddRow(new string[] {
                        "cpf",
                        "27960259267"});
            table1.AddRow(new string[] {
                        "email",
                        "elton@gmail.com"});
            table1.AddRow(new string[] {
                        "senha",
                        "Teste@123"});
            table1.AddRow(new string[] {
                        "senhaConfirmacao",
                        "Teste@123"});
#line 12
 testRunner.And("preenche os campos com os valores", ((string)(null)), table1, "E ");
#line 19
 testRunner.When("clicar no botao registrar", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 20
 testRunner.Then("Será registrado e redirecionado com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CadastroDeOrganizadorFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CadastroDeOrganizadorFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
